// <auto-generated />
namespace TournamentBuilder.Infrastructure.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class added_new_tables_and_rel_beetwen : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_new_tables_and_rel_beetwen));
        
        string IMigrationMetadata.Id
        {
            get { return "201709181153508_added_new_tables_and_rel_beetwen"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
