// <auto-generated />
namespace TournamentBuilder.Infrastructure.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changed_property_name : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changed_property_name));
        
        string IMigrationMetadata.Id
        {
            get { return "201709191207117_changed_property_name"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
