// <auto-generated />
namespace TournamentBuilder.Infrastructure.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class set_cascade_deleting : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(set_cascade_deleting));
        
        string IMigrationMetadata.Id
        {
            get { return "201709150902591_set_cascade_deleting"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
