// <auto-generated />
namespace TournamentBuilder.Infrastructure.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class change_unique : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change_unique));
        
        string IMigrationMetadata.Id
        {
            get { return "201709150847466_change_unique"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
